import { ListingType } from '../types/index';

/**
 * Sample listings with complete compatibility tags for demonstration and testing
 * These can be used to populate the Firebase database or as fallback data
 */
export const sampleListings: ListingType[] = [
  {
    id: 'sample-listing-1',
    title: 'Spacious 2 Bedroom in Downtown Santa Cruz',
    price: 1400,
    location: 'Downtown, Santa Cruz',
    description: 'Beautiful apartment with modern amenities, close to UCSC bus routes, cafes, and restaurants. Two large bedrooms with plenty of natural light. Shared living space with kitchen and balcony.',
    bedrooms: 2,
    bathrooms: 1,
    availableDate: new Date('2023-09-01'),
    imageURLs: [
      'https://via.placeholder.com/800x600?text=Downtown+Apartment',
      'https://via.placeholder.com/800x600?text=Kitchen',
      'https://via.placeholder.com/800x600?text=Bedroom',
      'https://via.placeholder.com/800x600?text=Bathroom'
    ],
    thumbnailURL: 'https://via.placeholder.com/800x600?text=Downtown+Apartment',
    amenities: ['parking', 'laundry', 'dishwasher', 'balcony'],
    utilities: ['water', 'garbage', 'internet'],
    ownerId: 'user-1',
    createdAt: { toDate: () => new Date() },
    favoriteCount: 12,
    pets: true,
    onCampus: false,
    address: '123 Pacific Ave, Santa Cruz, CA 95060',
    lat: 36.9741,
    lng: -122.0308,
    tags: {
      sleepSchedule: "10pm - 12am",
      wakeupSchedule: "7am - 9am",
      cleanliness: "Very tidy",
      noiseLevel: "Background noise/music",
      visitors: "Occasionally",
      studyHabits: "Home",
      lifestyle: ["Cooks often", "Vegetarian"]
    }
  },
  {
    id: 'sample-listing-2',
    title: 'Cozy Studio near West Cliff',
    price: 950,
    location: 'Westside, Santa Cruz',
    description: 'Charming studio apartment with ocean views. Perfect for students who want a quiet study space. Recently renovated with new appliances and fixtures.',
    bedrooms: 1,
    bathrooms: 1,
    availableDate: new Date('2023-08-15'),
    imageURLs: [
      'https://via.placeholder.com/800x600?text=Westside+Studio',
      'https://via.placeholder.com/800x600?text=Studio+Kitchen',
      'https://via.placeholder.com/800x600?text=Bath'
    ],
    thumbnailURL: 'https://via.placeholder.com/800x600?text=Westside+Studio',
    amenities: ['parking', 'furnished', 'patio'],
    utilities: ['all utilities included'],
    ownerId: 'user-2',
    createdAt: { toDate: () => new Date(Date.now() - 86400000) },
    favoriteCount: 18,
    pets: false,
    onCampus: false,
    address: '456 Ocean View Dr, Santa Cruz, CA 95062',
    lat: 36.9627,
    lng: -122.0000,
    tags: {
      sleepSchedule: "Before 10pm",
      wakeupSchedule: "Before 7am",
      cleanliness: "Very tidy",
      noiseLevel: "Silent",
      visitors: "Rarely",
      studyHabits: "Home",
      lifestyle: ["Wakes up early"]
    }
  },
  {
    id: 'sample-listing-3',
    title: 'Room in 4-Bedroom Apartment on Campus',
    price: 850,
    location: 'UC Santa Cruz',
    description: 'Single room available in a shared apartment in College Nine. Close to dining hall and campus facilities. Great community of students.',
    bedrooms: 1,
    bathrooms: 1,
    availableDate: new Date('2023-09-15'),
    imageURLs: [
      'https://via.placeholder.com/800x600?text=Campus+Housing',
      'https://via.placeholder.com/800x600?text=Dorm+Room',
      'https://via.placeholder.com/800x600?text=Common+Area'
    ],
    thumbnailURL: 'https://via.placeholder.com/800x600?text=Campus+Housing',
    amenities: ['furnished', 'meal plan available', 'campus shuttles'],
    utilities: ['all utilities included'],
    ownerId: 'user-3',
    createdAt: { toDate: () => new Date(Date.now() - 172800000) },
    favoriteCount: 9,
    pets: false,
    onCampus: true,
    address: '789 High St, Santa Cruz, CA 95064',
    lat: 36.9916,
    lng: -122.0583,
    tags: {
      sleepSchedule: "After 12am",
      wakeupSchedule: "After 9am",
      cleanliness: "Moderately tidy",
      noiseLevel: "Background noise/music",
      visitors: "Occasionally",
      studyHabits: "Library",
      lifestyle: ["Stays up late", "Drinks"]
    }
  },
  {
    id: 'sample-listing-4',
    title: '3 Bedroom House in Seabright with Garden',
    price: 2400,
    location: 'Seabright, Santa Cruz',
    description: 'Beautiful house close to the beach with a large backyard. Perfect for students who enjoy outdoor activities. Shared kitchen and living room with great natural light.',
    bedrooms: 3,
    bathrooms: 2,
    availableDate: new Date('2023-08-01'),
    imageURLs: [
      'https://via.placeholder.com/800x600?text=Seabright+House',
      'https://via.placeholder.com/800x600?text=Backyard',
      'https://via.placeholder.com/800x600?text=Living+Room',
      'https://via.placeholder.com/800x600?text=Kitchen+View'
    ],
    thumbnailURL: 'https://via.placeholder.com/800x600?text=Seabright+House',
    amenities: ['parking', 'laundry', 'backyard', 'garage'],
    utilities: ['water', 'garbage'],
    ownerId: 'user-4',
    createdAt: { toDate: () => new Date(Date.now() - 259200000) },
    favoriteCount: 24,
    pets: true,
    onCampus: false,
    address: '321 Soquel Ave, Santa Cruz, CA 95062',
    lat: 36.9599,
    lng: -121.9905,
    tags: {
      sleepSchedule: "10pm - 12am",
      wakeupSchedule: "7am - 9am",
      cleanliness: "Moderately tidy",
      noiseLevel: "Background noise/music",
      visitors: "Frequently",
      studyHabits: "Home",
      lifestyle: ["Cooks often", "Drinks", "Smokes"]
    }
  },
  {
    id: 'sample-listing-5',
    title: 'Room in Quiet Eastside Home',
    price: 1000,
    location: 'Eastside, Santa Cruz',
    description: 'Private room in a peaceful family home. Ideal for graduate students or serious undergrads. Lovely garden and close to Harbor.',
    bedrooms: 1,
    bathrooms: 1,
    availableDate: new Date('2023-07-20'),
    imageURLs: [
      'https://via.placeholder.com/800x600?text=Eastside+Room',
      'https://via.placeholder.com/800x600?text=Garden+View',
      'https://via.placeholder.com/800x600?text=Study+Area'
    ],
    thumbnailURL: 'https://via.placeholder.com/800x600?text=Eastside+Room',
    amenities: ['parking', 'laundry', 'furnished', 'garden access'],
    utilities: ['water', 'garbage', 'internet'],
    ownerId: 'user-5',
    createdAt: { toDate: () => new Date(Date.now() - 345600000) },
    favoriteCount: 15,
    pets: true,
    onCampus: false,
    address: '654 Bay St, Santa Cruz, CA 95060',
    lat: 36.9855,
    lng: -121.9584,
    tags: {
      sleepSchedule: "Before 10pm",
      wakeupSchedule: "Before 7am",
      cleanliness: "Very tidy",
      noiseLevel: "Silent",
      visitors: "Rarely",
      studyHabits: "Library",
      lifestyle: ["Wakes up early"]
    }
  },
  {
    id: 'sample-listing-6',
    title: 'Modern Apartment in Capitola Village',
    price: 1700,
    location: 'Capitola, Santa Cruz',
    description: 'Recently renovated apartment with ocean views. Walking distance to Capitola Beach and restaurants. Perfect for students who enjoy beach life.',
    bedrooms: 2,
    bathrooms: 1,
    availableDate: new Date('2023-08-10'),
    imageURLs: ['https://via.placeholder.com/800x600?text=Capitola+Apartment'],
    amenities: ['parking', 'laundry', 'dishwasher', 'balcony'],
    utilities: ['water', 'garbage'],
    ownerId: 'user-6',
    createdAt: { toDate: () => new Date(Date.now() - 432000000) },
    favoriteCount: 20,
    pets: false,
    onCampus: false,
    address: '987 Mission St, Santa Cruz, CA 95060',
    lat: 36.9698,
    lng: -121.9539,
    tags: {
      sleepSchedule: "10pm - 12am",
      wakeupSchedule: "7am - 9am",
      cleanliness: "Moderately tidy",
      noiseLevel: "Background noise/music",
      visitors: "Occasionally",
      studyHabits: "Other",
      lifestyle: ["Cooks often"]
    }
  },
  {
    id: 'sample-listing-7',
    title: 'Sunny Room in Shared Westside House',
    price: 950,
    location: 'Westside, Santa Cruz',
    description: 'Bright room available in a 4-bedroom house shared with UCSC students. Close to West Cliff and Natural Bridges Beach.',
    bedrooms: 1,
    bathrooms: 1.5,
    availableDate: new Date('2023-07-15'),
    imageURLs: ['https://via.placeholder.com/800x600?text=Westside+Room'],
    amenities: ['parking', 'laundry', 'backyard', 'storage'],
    utilities: ['all utilities included'],
    ownerId: 'user-7',
    createdAt: { toDate: () => new Date(Date.now() - 518400000) },
    favoriteCount: 11,
    pets: true,
    onCampus: false,
    address: '456 Ocean View Dr, Santa Cruz, CA 95062',
    lat: 36.9627,
    lng: -122.0000,
    tags: {
      sleepSchedule: "After 12am",
      wakeupSchedule: "After 9am",
      cleanliness: "Messy",
      noiseLevel: "Background noise/music",
      visitors: "Frequently",
      studyHabits: "Library",
      lifestyle: ["Stays up late", "Drinks", "Vegetarian"]
    }
  },
  {
    id: 'sample-listing-8',
    title: 'Graduate Housing at UC Santa Cruz',
    price: 1100,
    location: 'UC Santa Cruz',
    description: 'Graduate student housing available on campus. Private room in a shared apartment with other graduate students.',
    bedrooms: 1,
    bathrooms: 1,
    availableDate: new Date('2023-09-01'),
    imageURLs: ['https://via.placeholder.com/800x600?text=Grad+Housing'],
    amenities: ['furnished', 'laundry', 'study spaces', 'gym access'],
    utilities: ['all utilities included'],
    ownerId: 'user-8',
    createdAt: { toDate: () => new Date(Date.now() - 604800000) },
    favoriteCount: 8,
    pets: false,
    onCampus: true,
    address: '789 High St, Santa Cruz, CA 95064',
    lat: 36.9900,
    lng: -122.0600,
    tags: {
      sleepSchedule: "10pm - 12am",
      wakeupSchedule: "7am - 9am",
      cleanliness: "Very tidy",
      noiseLevel: "Silent",
      visitors: "Occasionally",
      studyHabits: "Home",
      lifestyle: ["Cooks often"]
    }
  },
  {
    id: 'sample-listing-9',
    title: 'Cozy Downtown Loft',
    price: 1250,
    location: 'Downtown, Santa Cruz',
    description: 'Charming loft in the heart of downtown. Walking distance to restaurants, shops, and bus routes to UCSC.',
    bedrooms: 1,
    bathrooms: 1,
    availableDate: new Date('2023-08-05'),
    imageURLs: ['https://via.placeholder.com/800x600?text=Downtown+Loft'],
    amenities: ['laundry', 'dishwasher', 'high ceilings'],
    utilities: ['water', 'garbage', 'internet'],
    ownerId: 'user-9',
    createdAt: { toDate: () => new Date(Date.now() - 691200000) },
    favoriteCount: 16,
    pets: false,
    onCampus: false,
    address: '123 Pacific Ave, Santa Cruz, CA 95060',
    lat: 36.9741,
    lng: -122.0308,
    tags: {
      sleepSchedule: "10pm - 12am",
      wakeupSchedule: "7am - 9am",
      cleanliness: "Moderately tidy",
      noiseLevel: "Background noise/music",
      visitors: "Occasionally",
      studyHabits: "Home",
      lifestyle: ["Cooks often", "Vegetarian"]
    }
  },
  {
    id: 'sample-listing-10',
    title: 'Room in Peaceful Eastside Cottage',
    price: 1050,
    location: 'Eastside, Santa Cruz',
    description: 'Serene room in a cottage-style home. Great for students who need quiet study space. Close to Pleasure Point and East Cliff.',
    bedrooms: 1,
    bathrooms: 1,
    availableDate: new Date('2023-07-25'),
    imageURLs: ['https://via.placeholder.com/800x600?text=Eastside+Cottage'],
    amenities: ['parking', 'garden', 'patio', 'storage'],
    utilities: ['water', 'garbage', 'internet'],
    ownerId: 'user-10',
    createdAt: { toDate: () => new Date(Date.now() - 777600000) },
    favoriteCount: 13,
    pets: true,
    onCampus: false,
    address: '654 Bay St, Santa Cruz, CA 95060',
    lat: 36.9855,
    lng: -121.9584,
    tags: {
      sleepSchedule: "Before 10pm",
      wakeupSchedule: "Before 7am",
      cleanliness: "Very tidy",
      noiseLevel: "Silent",
      visitors: "Rarely",
      studyHabits: "Home",
      lifestyle: ["Wakes up early"]
    }
  }
]; 